create table if not exists public.city_leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid,
  city_id text not null,
  player_name text,
  city_name text not null default 'NPS City',
  room_code text,
  money bigint not null default 0,
  happiness integer not null default 0,
  environment integer not null default 0,
  esg_score integer not null default 0,
  power_reliability integer not null default 0,
  population integer not null default 0,
  game_state text,
  is_public boolean not null default true,
  updated_at timestamptz not null default now()
);

create unique index if not exists city_leaderboard_user_city_idx
  on public.city_leaderboard (user_id, city_id);

create index if not exists city_leaderboard_room_code_idx
  on public.city_leaderboard (room_code);

alter table public.city_leaderboard enable row level security;

create or replace function public.update_city_leaderboard_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists city_leaderboard_updated_at on public.city_leaderboard;

create trigger city_leaderboard_updated_at
  before update on public.city_leaderboard
  for each row
  execute function public.update_city_leaderboard_updated_at();

do $$
begin
  drop policy if exists "Anyone can view public leaderboard" on public.city_leaderboard;
  drop policy if exists "Users can insert own city" on public.city_leaderboard;
  drop policy if exists "Users can update own city" on public.city_leaderboard;
  drop policy if exists "Anyone can read public city leaderboard" on public.city_leaderboard;
  drop policy if exists "Anyone can create city leaderboard rows" on public.city_leaderboard;
  drop policy if exists "Anyone can update city leaderboard rows" on public.city_leaderboard;
  drop policy if exists "Anyone can delete city leaderboard rows" on public.city_leaderboard;
  drop policy if exists "Users can delete own city" on public.city_leaderboard;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'city_leaderboard'
      and policyname = 'Anyone can read public city leaderboard'
  ) then
    create policy "Anyone can read public city leaderboard"
      on public.city_leaderboard
      for select
      to anon, authenticated
      using (is_public = true);
  end if;

  create policy "Users can insert own city"
    on public.city_leaderboard
    for insert
    to authenticated
    with check (auth.uid() = user_id);

  create policy "Users can update own city"
    on public.city_leaderboard
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

  create policy "Users can delete own city"
    on public.city_leaderboard
    for delete
    to authenticated
    using (auth.uid() = user_id);
end $$;
